
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."ArtistType" (
    "ArtistTypeId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name" character varying NOT NULL
);

ALTER TABLE "public"."ArtistType" OWNER TO "postgres";

ALTER TABLE "public"."ArtistType" ALTER COLUMN "ArtistTypeId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ArtistType_ArtistTypeId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Artists" (
    "ArtistId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name" character varying NOT NULL
);

ALTER TABLE "public"."Artists" OWNER TO "postgres";

ALTER TABLE "public"."Artists" ALTER COLUMN "ArtistId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Artists_ArtistId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Contact" (
    "MessageId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name" character varying NOT NULL,
    "Email" character varying NOT NULL,
    "Message" "text" NOT NULL,
    "ReferringPage" character varying NOT NULL,
    "FormSource" character varying
);

ALTER TABLE "public"."Contact" OWNER TO "postgres";

ALTER TABLE "public"."Contact" ALTER COLUMN "MessageId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Contact_MessageId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."Genres" (
    "GenreId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name" character varying NOT NULL
);

ALTER TABLE "public"."Genres" OWNER TO "postgres";

ALTER TABLE "public"."Genres" ALTER COLUMN "GenreId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Genres_GenreId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."ListenHistory" (
    "ListenHistoryId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ListenDate" timestamp with time zone NOT NULL,
    "SongTitle" "text" NOT NULL,
    "Artist" "text",
    "Album" "text"
);

ALTER TABLE "public"."ListenHistory" OWNER TO "postgres";

ALTER TABLE "public"."ListenHistory" ALTER COLUMN "ListenHistoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ListenHistory_ListenHistoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."RecordToArtist" (
    "RecordToArtistId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "RecordId" bigint NOT NULL,
    "ArtistId" bigint NOT NULL,
    "ArtistTypeId" bigint NOT NULL
);

ALTER TABLE "public"."RecordToArtist" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."RecordToGenre" (
    "RecordToGenreId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "RecordId" bigint NOT NULL,
    "GenreId" bigint NOT NULL
);

ALTER TABLE "public"."RecordToGenre" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."Records" (
    "RecordId" bigint NOT NULL,
    "DateCreated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "DateUpdated" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name" character varying NOT NULL,
    "Year" integer,
    "ImageUrl" "text",
    "DiscogsUrl" "text"
);

ALTER TABLE "public"."Records" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."RecordData" AS
 SELECT "Records"."RecordId",
    "Records"."Name" AS "RecordName",
    "Records"."Year",
    "Records"."ImageUrl",
    "Records"."DiscogsUrl",
    "Artists"."ArtistId",
    "Artists"."Name" AS "ArtistName",
    "string_agg"("concat"("Genres"."GenreId", '%', "Genres"."Name"), ','::"text") AS "Genres"
   FROM (((("public"."Records"
     JOIN "public"."RecordToArtist" ON (("Records"."RecordId" = "RecordToArtist"."RecordId")))
     JOIN "public"."Artists" ON (("RecordToArtist"."ArtistId" = "Artists"."ArtistId")))
     JOIN "public"."RecordToGenre" ON (("Records"."RecordId" = "RecordToGenre"."RecordId")))
     JOIN "public"."Genres" ON (("RecordToGenre"."GenreId" = "Genres"."GenreId")))
  GROUP BY "Records"."RecordId", "Records"."Name", "Records"."Year", "Records"."ImageUrl", "Records"."DiscogsUrl", "Artists"."ArtistId", "Artists"."Name";

ALTER TABLE "public"."RecordData" OWNER TO "postgres";

ALTER TABLE "public"."RecordToArtist" ALTER COLUMN "RecordToArtistId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RecordToArtist_RecordToArtistId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."RecordToGenre" ALTER COLUMN "RecordToGenreId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."RecordToGenre_RecordToGenreId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Records" ALTER COLUMN "RecordId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Records_RecordId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."ArtistType"
    ADD CONSTRAINT "ArtistType_Name_key" UNIQUE ("Name");

ALTER TABLE ONLY "public"."ArtistType"
    ADD CONSTRAINT "ArtistType_pkey" PRIMARY KEY ("ArtistTypeId");

ALTER TABLE ONLY "public"."Artists"
    ADD CONSTRAINT "Artists_Name_key" UNIQUE ("Name");

ALTER TABLE ONLY "public"."Artists"
    ADD CONSTRAINT "Artists_pkey" PRIMARY KEY ("ArtistId");

ALTER TABLE ONLY "public"."Contact"
    ADD CONSTRAINT "Contact_pkey" PRIMARY KEY ("MessageId");

ALTER TABLE ONLY "public"."Genres"
    ADD CONSTRAINT "Genres_Name_key" UNIQUE ("Name");

ALTER TABLE ONLY "public"."Genres"
    ADD CONSTRAINT "Genres_pkey" PRIMARY KEY ("GenreId");

ALTER TABLE ONLY "public"."ListenHistory"
    ADD CONSTRAINT "ListenHistory_pkey" PRIMARY KEY ("ListenHistoryId");

ALTER TABLE ONLY "public"."RecordToArtist"
    ADD CONSTRAINT "RecordToArtist_pkey" PRIMARY KEY ("RecordToArtistId");

ALTER TABLE ONLY "public"."RecordToGenre"
    ADD CONSTRAINT "RecordToGenre_pkey" PRIMARY KEY ("RecordToGenreId");

ALTER TABLE ONLY "public"."Records"
    ADD CONSTRAINT "Records_pkey" PRIMARY KEY ("RecordId");

CREATE OR REPLACE TRIGGER "date_updated_artist_type" BEFORE UPDATE ON "public"."ArtistType" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_artists" BEFORE UPDATE ON "public"."Artists" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_contact" BEFORE UPDATE ON "public"."Contact" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_genres" BEFORE UPDATE ON "public"."Genres" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_listen_history" BEFORE UPDATE ON "public"."ListenHistory" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_record_to_artist" BEFORE UPDATE ON "public"."RecordToArtist" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_record_to_genre" BEFORE UPDATE ON "public"."RecordToGenre" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

CREATE OR REPLACE TRIGGER "date_updated_records" BEFORE UPDATE ON "public"."Records" FOR EACH ROW EXECUTE FUNCTION "extensions"."moddatetime"('DateUpdated');

ALTER TABLE ONLY "public"."RecordToArtist"
    ADD CONSTRAINT "RecordToArtist_ArtistId_fkey" FOREIGN KEY ("ArtistId") REFERENCES "public"."Artists"("ArtistId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."RecordToArtist"
    ADD CONSTRAINT "RecordToArtist_ArtistTypeId_fkey" FOREIGN KEY ("ArtistTypeId") REFERENCES "public"."ArtistType"("ArtistTypeId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."RecordToArtist"
    ADD CONSTRAINT "RecordToArtist_RecordId_fkey" FOREIGN KEY ("RecordId") REFERENCES "public"."Records"("RecordId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."RecordToGenre"
    ADD CONSTRAINT "RecordToGenre_GenreId_fkey" FOREIGN KEY ("GenreId") REFERENCES "public"."Genres"("GenreId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."RecordToGenre"
    ADD CONSTRAINT "RecordToGenre_RecordId_fkey" FOREIGN KEY ("RecordId") REFERENCES "public"."Records"("RecordId") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."ArtistType" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Artists" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Contact" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."ArtistType" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Artists" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Contact" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Genres" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."ListenHistory" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."RecordToArtist" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."RecordToGenre" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."Records" FOR SELECT USING (true);

ALTER TABLE "public"."Genres" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."ListenHistory" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."RecordToArtist" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."RecordToGenre" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."Records" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."ArtistType" TO "anon";
GRANT ALL ON TABLE "public"."ArtistType" TO "authenticated";
GRANT ALL ON TABLE "public"."ArtistType" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ArtistType_ArtistTypeId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ArtistType_ArtistTypeId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ArtistType_ArtistTypeId_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Artists" TO "anon";
GRANT ALL ON TABLE "public"."Artists" TO "authenticated";
GRANT ALL ON TABLE "public"."Artists" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Artists_ArtistId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Artists_ArtistId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Artists_ArtistId_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Contact" TO "anon";
GRANT ALL ON TABLE "public"."Contact" TO "authenticated";
GRANT ALL ON TABLE "public"."Contact" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Contact_MessageId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Contact_MessageId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Contact_MessageId_seq" TO "service_role";

GRANT ALL ON TABLE "public"."Genres" TO "anon";
GRANT ALL ON TABLE "public"."Genres" TO "authenticated";
GRANT ALL ON TABLE "public"."Genres" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Genres_GenreId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Genres_GenreId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Genres_GenreId_seq" TO "service_role";

GRANT ALL ON TABLE "public"."ListenHistory" TO "anon";
GRANT ALL ON TABLE "public"."ListenHistory" TO "authenticated";
GRANT ALL ON TABLE "public"."ListenHistory" TO "service_role";

GRANT ALL ON SEQUENCE "public"."ListenHistory_ListenHistoryId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ListenHistory_ListenHistoryId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ListenHistory_ListenHistoryId_seq" TO "service_role";

GRANT ALL ON TABLE "public"."RecordToArtist" TO "anon";
GRANT ALL ON TABLE "public"."RecordToArtist" TO "authenticated";
GRANT ALL ON TABLE "public"."RecordToArtist" TO "service_role";

GRANT ALL ON TABLE "public"."RecordToGenre" TO "anon";
GRANT ALL ON TABLE "public"."RecordToGenre" TO "authenticated";
GRANT ALL ON TABLE "public"."RecordToGenre" TO "service_role";

GRANT ALL ON TABLE "public"."Records" TO "anon";
GRANT ALL ON TABLE "public"."Records" TO "authenticated";
GRANT ALL ON TABLE "public"."Records" TO "service_role";

GRANT ALL ON TABLE "public"."RecordData" TO "anon";
GRANT ALL ON TABLE "public"."RecordData" TO "authenticated";
GRANT ALL ON TABLE "public"."RecordData" TO "service_role";

GRANT ALL ON SEQUENCE "public"."RecordToArtist_RecordToArtistId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RecordToArtist_RecordToArtistId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RecordToArtist_RecordToArtistId_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."RecordToGenre_RecordToGenreId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."RecordToGenre_RecordToGenreId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."RecordToGenre_RecordToGenreId_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."Records_RecordId_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Records_RecordId_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Records_RecordId_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
